import grey from "@/assets/images/colors_page/grey.jpg";

export const product_colors = [
  {
    id: 1,
    color_cat_title: '3/8" Single Cell',
    colors: [
      {
        id: 1,
        color_code: "#dddfff",
        name: "Red",
        price: 15.25,
        image: grey.src,
      },
      {
        id: 2,
        color_code: "#dddf22",
        name: "Yellow SCC26666",
        price: 10.15,
        image: grey.src,
      },
      {
        id: 3,
        color_code: "#0d1aca",
        name: "Blue SCC26666",
        price: 14.25,
        image: grey.src,
      },
      {
        id: 4,
        color_code: "#858dfc",
        name: "Light Blue SCC26666",
        price: 12.1,
        image: grey.src,
      },
      {
        id: 6,
        color_code: "#d66a17",
        name: "Dark Orange SCC26666",
        price: 25.15,
        image: grey.src,
      },
      {
        id: 7,
        color_code: "#5cdb35",
        name: "Parrot Green SCC26666",
        price: 13.15,
        image: grey.src,
      },
      {
        id: 8,
        color_code: "#e50c30",
        name: "Red SCC26666",
        price: 16.45,
        image: grey.src,
      },
      {
        id: 9,
        color_code: "#0cade8",
        name: "Sky Blue SCC26666",
        price: 24.27,
        image: grey.src,
      },
      {
        id: 10,
        color_code: "#0cade8",
        name: "Sky Blue SCC26666",
        price: 24.27,
        image: grey.src,
      },
      {
        id: 11,
        color_code: "#0cade8",
        name: "Sky Blue SCC26666",
        price: 24.27,
        image: grey.src,
      },
      {
        id: 12,
        color_code: "#0cade8",
        name: "Sky Blue SCC26666",
        price: 24.27,
        image: grey.src,
      },
      {
        id: 13,
        color_code: "#0cade8",
        name: "Sky Blue SCC26666",
        price: 24.27,
        image: grey.src,
      },
      {
        id: 14,
        color_code: "#0cade8",
        name: "Sky Blue SCC26666",
        price: 24.27,
        image: grey.src,
      },
      {
        id: 15,
        color_code: "#0cade8",
        name: "Sky Blue SCC26666",
        price: 24.27,
        image: grey.src,
      },
    ],
  },
  {
    id: 2,
    color_cat_title: '3/4" Single Cell',
    colors: [
      {
        id: 16,
        color_code: "#dddfff",
        name: "Green",
        price: 15.25,
        image: grey.src,
      },
      {
        id: 17,
        color_code: "#dddf22",
        name: "Yellow SCC26666",
        price: 10.15,
        image: grey.src,
      },
      {
        id: 18,
        color_code: "#0d1aca",
        name: "Blue SCC26666",
        price: 14.25,
        image: grey.src,
      },
      {
        id: 19,
        color_code: "#858dfc",
        name: "Light Blue SCC26666",
        price: 12.1,
        image: grey.src,
      },
      {
        id: 20,
        color_code: "#d66a17",
        name: "Dark Orange SCC26666",
        price: 25.15,
        image: grey.src,
      },
      {
        id: 21,
        color_code: "#5cdb35",
        name: "Parrot Green SCC26666",
        price: 13.15,
        image: grey.src,
      },
      {
        id: 22,
        color_code: "#e50c30",
        name: "Red SCC26666",
        price: 16.45,
        image: grey.src,
      },
      {
        id: 23,
        color_code: "#0cade8",
        name: "Sky Blue SCC26666",
        price: 24.27,
        image: grey.src,
      },
    ],
  },
];
